name: Shelly Device Scanner
version: "0.6.3"
slug: shelly_scanner
description: Scan and manage Shelly devices on your network
url: "https://github.com/filmgarage/ha-addon-shelly-scanner"
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_port: 8099
host_network: true
ports:
  8099/tcp: 8099
homeassistant_api: true
hassio_api: true
hassio_role: admin
auth_api: true
map:
  - addon_config:rw
panel_icon: mdi:lightbulb-group
panel_title: Shelly Scanner
image: ghcr.io/filmgarage/shelly-scanner-{arch}
options:
  admin_password: ""
  network_range: ""
schema:
  admin_password: password
  network_range: str?
