name: Shelly Device Scanner
version: "0.5.3"
slug: shelly_scanner
description: Scan and manage Shelly devices on your network
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
host_network: true
ingress: true
ingress_port: 8099
panel_icon: mdi:lightbulb-group
panel_title: Shelly Scanner
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface (when not using ingress)
options:
  admin_password: ""
schema:
  admin_password: password
