name: Shelly Device Scanner
version: "1.0.0"
slug: shelly_scanner
description: Scan and manage Shelly devices on your network
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
webui: http://[HOST]:[PORT:8099]
panel_icon: mdi:lightbulb-group
panel_title: Shelly Scanner
options:
  admin_password: ""
schema:
  admin_password: password
image: ghcr.io/{username}/hassio-shelly-scanner-{arch}
