name: Shelly Device Scanner
version: "0.5.15"
url: https://github.com/filmgarage/ha-addon-shelly-scanner
slug: shelly_scanner
description: Scan and manage Shelly devices on your network
ingress: True
ingress_port: 8099
ingress_root: "/"
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
hassio_api: true
hassio_role: admin
auth_api: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
panel_icon: mdi:lightbulb-group
panel_title: Shelly Scanner
options:
  admin_password: ""
  network_range: ""
schema:
  admin_password: password
  network_range: str?
