name: Shelly Device Scanner
version: "0.5.14"
slug: shelly_scanner
description: Scan and manage Shelly devices on your network
arch:
  - aarch64
  - amd64
init: false
host_network: true
ingress: true
ingress_port: 8099
ingress_stream: true
panel_icon: mdi:lightbulb-group
panel_title: Shelly Scanner
options:
  admin_password: ""
schema:
  admin_password: password
